//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace Data {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class SysRole {

		/// <summary>
		/// 描述
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(350)")]
		public string Description { get; set; } = string.Empty;

		/// <summary>
		/// 启用数据授权
		/// </summary>
		[JsonProperty]
		public bool EnableData { get; set; }

		/// <summary>
		/// 启用字段授权
		/// </summary>
		[JsonProperty]
		public bool EnableField { get; set; }

		[JsonProperty]
		public bool HideUnionQuery { get; set; }

		[JsonProperty]
		public Guid ID { get; set; }

		/// <summary>
		/// 禁用角色
		/// </summary>
		[JsonProperty]
		public bool IsDisable { get; set; }

		/// <summary>
		/// 角色名称
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(100)")]
		public string Name { get; set; } = string.Empty;

		/// <summary>
		/// 繁体名称
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(100)")]
		public string Name_CHT { get; set; } = string.Empty;

		/// <summary>
		/// 英文名称
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(100)")]
		public string Name_EN { get; set; } = string.Empty;

	}

}
