//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace Data {

	[JsonObject(MemberSerialization.OptIn)]
	public partial class SysUser {

		[JsonProperty]
		public DateTime? Activated { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string ADUser { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(256)")]
		public string Avatar { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? Birthday { get; set; }

		/// <summary>
		/// 登录代码
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(30)")]
		public string Code { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(256)")]
		public string Company { get; set; } = string.Empty;

		[JsonProperty]
		public DateTime? Created { get; set; }

		[JsonProperty, Column(DbType = "varchar(128)")]
		public string CreateSource { get; set; } = string.Empty;

		/// <summary>
		/// 部门ID
		/// </summary>
		[JsonProperty]
		public Guid? DeptID { get; set; }

		[JsonProperty, Column(DbType = "varchar(50)")]
		public string DingDing { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(256)")]
		public string DingDingOpenid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(100)")]
		public string EMail { get; set; } = string.Empty;

		/// <summary>
		/// 启用数据授权
		/// </summary>
		[JsonProperty]
		public bool EnableData { get; set; }

		/// <summary>
		/// 说明
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(200)")]
		public string Explain { get; set; } = string.Empty;

		[JsonProperty]
		public Guid? ExtrudingMachineID { get; set; }

		[JsonProperty, Column(DbType = "varchar(16)")]
		public string Gender { get; set; } = string.Empty;

		[JsonProperty]
		public Guid ID { get; set; }

		[JsonProperty]
		public bool IsAudit { get; set; }

		/// <summary>
		/// 停用
		/// </summary>
		[JsonProperty]
		public bool IsDisable { get; set; }

		[JsonProperty]
		public DateTime? Logged { get; set; }

		[JsonProperty, Column(DbType = "varchar(30)")]
		public string Mobile { get; set; } = string.Empty;

		/// <summary>
		/// 用户名
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(100)")]
		public string Name { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(100)")]
		public string Nickname { get; set; } = string.Empty;

		/// <summary>
		/// 密码
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(100)")]
		public string Password { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(10)")]
		public string PlantArea { get; set; } = string.Empty;

		[JsonProperty]
		public Guid? PlantDeptId { get; set; }

		[JsonProperty, Column(DbType = "nvarchar(15)")]
		public string QQ { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(256)")]
		public string QQOpenid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(512)")]
		public string Remark { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(36)")]
		public string Salt { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(1024)")]
		public string Signature { get; set; } = string.Empty;

		/// <summary>
		/// 状态
		/// </summary>
		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string Status { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(100)")]
		public string Team { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(256)")]
		public string WeChatOpenid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "varchar(256)")]
		public string WeChatUnionid { get; set; } = string.Empty;

		[JsonProperty, Column(DbType = "nvarchar(50)")]
		public string WeiXinWork { get; set; } = string.Empty;

	}

}
